export interface ILaporanPesanan {
  tanggal: string;
  namaCust: string;
  noHpCust: string;
  csDesk: string;
  total: number;
  tglBayar: string;
  tipeBayar: string;
  bukti: string;
  file: string;
  sisaTagihan: string | number;
  status: string;
}

export const dummyLaporanPesanan: ILaporanPesanan[] = [
  {
    tanggal: "1/6/2023",
    namaCust: "Andi Purnomo",
    noHpCust: "08123456789",
    csDesk: "Miahana",
    total: 1200000,
    tglBayar: "2/6/2023",
    tipeBayar: "Cash",
    bukti: "view",
    file: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/SpongeBob_SquarePants_character.svg/1200px-SpongeBob_SquarePants_character.svg.png",
    sisaTagihan: "-",
    status: "lunas",
  },
  {
    tanggal: "1/6/2023",
    namaCust: "Astuti Putri",
    noHpCust: "08987654321",
    csDesk: "Miahana",
    total: 1200000,
    tglBayar: "2/6/2023",
    tipeBayar: "Cash",
    bukti: "view",
    file: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/SpongeBob_SquarePants_character.svg/1200px-SpongeBob_SquarePants_character.svg.png",
    sisaTagihan: "-",
    status: "lunas",
  },
  {
    tanggal: "1/6/2023",
    namaCust: "Kuntoro Joyo",
    noHpCust: "0965643287",
    csDesk: "ikasept",
    total: 3981000,
    tglBayar: "1/6/2023",
    tipeBayar: "TF",
    bukti: "view",
    file: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/SpongeBob_SquarePants_character.svg/1200px-SpongeBob_SquarePants_character.svg.png",
    sisaTagihan: "-",
    status: "lunas",
  },
  {
    tanggal: "2/6/2023",
    namaCust: "Puput Alisha",
    noHpCust: "08776312321",
    csDesk: "ikasept",
    total: 4700000,
    tglBayar: "2/6/2023",
    tipeBayar: "TF",
    bukti: "view",
    file: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/SpongeBob_SquarePants_character.svg/1200px-SpongeBob_SquarePants_character.svg.png",
    sisaTagihan: "-",
    status: "lunas",
  },
  {
    tanggal: "2/6/2023",
    namaCust: "Raden Saleh",
    noHpCust: "086721316723",
    csDesk: "aguswin",
    total: 11325000,
    tglBayar: "2/6/2023",
    tipeBayar: "TF",
    bukti: "view",
    file: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/SpongeBob_SquarePants_character.svg/1200px-SpongeBob_SquarePants_character.svg.png",
    sisaTagihan: 5000000,
    status: "belum lunas",
  },
  {
    tanggal: "3/6/2023",
    namaCust: "Astuti Putri",
    noHpCust: "08987654321",
    csDesk: "Miahana",
    total: 2750000,
    tglBayar: "3/6/2023",
    tipeBayar: "Cash",
    bukti: "view",
    file: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/SpongeBob_SquarePants_character.svg/1200px-SpongeBob_SquarePants_character.svg.png",
    sisaTagihan: "-",
    status: "lunas",
  },
  {
    tanggal: "3/6/2023",
    namaCust: "Puput Alisha",
    noHpCust: "08776312321",
    csDesk: "aguswin",
    total: 2590000,
    tglBayar: "6/6/2023",
    tipeBayar: "TF",
    bukti: "view",
    file: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/SpongeBob_SquarePants_character.svg/1200px-SpongeBob_SquarePants_character.svg.png",
    sisaTagihan: "-",
    status: "lunas",
  },
  {
    tanggal: "3/6/2023",
    namaCust: "Kuntoro Joyo",
    noHpCust: "0965643287",
    csDesk: "ikasept",
    total: 15750000,
    tglBayar: "10/6/2023",
    tipeBayar: "TF",
    bukti: "view",
    file: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/SpongeBob_SquarePants_character.svg/1200px-SpongeBob_SquarePants_character.svg.png",
    sisaTagihan: "-",
    status: "lunas",
  },
  {
    tanggal: "4/6/2023",
    namaCust: "Astuti Putri",
    noHpCust: "08987654321",
    csDesk: "Miahana",
    total: 2750000,
    tglBayar: "4/6/2023",
    tipeBayar: "Cash",
    bukti: "view",
    file: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/SpongeBob_SquarePants_character.svg/1200px-SpongeBob_SquarePants_character.svg.png",
    sisaTagihan: "-",
    status: "lunas",
  },
  {
    tanggal: "4/6/2023",
    namaCust: "Marella Putri",
    noHpCust: "08671238231",
    csDesk: "ikasept",
    total: 15385000,
    tglBayar: "14/6/2023",
    tipeBayar: "TF",
    bukti: "view",
    file: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/SpongeBob_SquarePants_character.svg/1200px-SpongeBob_SquarePants_character.svg.png",
    sisaTagihan: 6461700,
    status: "belum lunas",
  },
  {
    tanggal: "5/6/2023",
    namaCust: "Puput Alisha",
    noHpCust: "08776312321",
    csDesk: "aguswin",
    total: 4700000,
    tglBayar: "5/6/2023",
    tipeBayar: "TF",
    bukti: "view",
    file: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/SpongeBob_SquarePants_character.svg/1200px-SpongeBob_SquarePants_character.svg.png",
    sisaTagihan: "-",
    status: "lunas",
  },
  {
    tanggal: "5/6/2023",
    namaCust: "Puput Alisha",
    noHpCust: "08776312321",
    csDesk: "aguswin",
    total: 4700000,
    tglBayar: "5/6/2023",
    tipeBayar: "TF",
    bukti: "view",
    file: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/SpongeBob_SquarePants_character.svg/1200px-SpongeBob_SquarePants_character.svg.png",
    sisaTagihan: "-",
    status: "lunas",
  },
  {
    tanggal: "7/6/2023",
    namaCust: "Astuti Putri",
    noHpCust: "08987654321",
    csDesk: "Miahana",
    total: 6700000,
    tglBayar: "7/6/2023",
    tipeBayar: "Cash",
    bukti: "view",
    file: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/SpongeBob_SquarePants_character.svg/1200px-SpongeBob_SquarePants_character.svg.png",
    sisaTagihan: "-",
    status: "lunas",
  },
  {
    tanggal: "7/6/2023",
    namaCust: "Kuntoro Joyo",
    noHpCust: "0965643287",
    csDesk: "Miahana",
    total: 3400000,
    tglBayar: "7/6/2023",
    tipeBayar: "TF",
    bukti: "view",
    file: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/SpongeBob_SquarePants_character.svg/1200px-SpongeBob_SquarePants_character.svg.png",
    sisaTagihan: "-",
    status: "lunas",
  },
  {
    tanggal: "8/6/2023",
    namaCust: "Andi Purnomo",
    noHpCust: "0965643287",
    csDesk: "Miahana",
    total: 1200000,
    tglBayar: "-",
    tipeBayar: "-",
    bukti: "-",
    file: "-",
    sisaTagihan: "1.200.000",
    status: "belum lunas",
  },
];

export enum PageEnum {
  list,
  add,
  edit,
}
